%% COMPARE_BASELINE_OASIS_ONE_NEURON_ALL_FPS.m
% Goal:
%   Compare the simple baseline model and OASIS on one neuron
%   across multiple sampling rates.
%
% Current scope:
%   - One neuron
%   - Four sampling rates: 100, 50, 20, 10 Hz
%   - Two models:
%       1. Simple baseline
%       2. OASIS
%   - Two evaluation modes:
%       1. spike_bins
%       2. burst_onsets
%
% Output:
%   Prints results to the MATLAB console.
%   Saves a detailed CSV table to results/tables/.

clear; clc; close all;

%% Add project paths

% Project source functions:
%   downsample_calcium_and_spikes()
%   run_simple_baseline()
%   run_oasis_model()
%   evaluate_event_prediction()
addpath(fullfile('..', 'src'));

% OASIS external toolbox
addpath(genpath(fullfile('..', 'external', 'OASIS_matlab')));

%% Load data

dataset_file = fullfile('..', 'data', 'MockData', 'data.1.train.preprocessed.mat');

raw = load(dataset_file);
data = raw.data;

%% Choose neuron

neuron_idx = 1;

rec = data{neuron_idx};

calcium = double(rec.calcium(:));
spikes = double(rec.spikes(:));
original_fps = double(rec.fps);

%% Sampling rates to test

target_fps_list = [100, 50, 20, 10];

%% Evaluation settings

% A predicted event is counted as correct if it is within this time window
% of a true event.
tolerance_sec = 0.10;

% In burst-onset mode, spike bins separated by less than this gap are treated
% as part of the same burst/activity episode.
burst_gap_sec = 0.10;

evaluation_modes = {'spike_bins', 'burst_onsets'};

%% Model 1: Simple baseline parameters

baseline_params = struct();

baseline_params.smoothing_window_sec = 0.2;
baseline_params.derivative_weight = 0.7;
baseline_params.amplitude_weight = 0.3;
baseline_params.event_score_threshold = 0.9;
baseline_params.min_event_distance_sec = 0.10;

%% Model 2: OASIS parameters

oasis_params = struct();

% OASIS internal deconvolution settings
oasis_params.ar_model = 'ar1';
oasis_params.method = 'foopsi';
oasis_params.optimize_b = true;
oasis_params.optimize_pars = true;

% OASIS event-conversion settings.
% These are not final. We will optimize them later.
oasis_params.oasis_threshold_z = 1.5;
oasis_params.min_event_distance_sec = 0.10;

%% Prepare results table

% One row per:
%   sampling rate x model x evaluation mode
results_table = table();

%% Main loop across sampling rates

for fps_idx = 1:length(target_fps_list)

    target_fps = target_fps_list(fps_idx);

    fprintf('\n============================================================\n');
    fprintf('Processing neuron %d at target %.1f Hz\n', neuron_idx, target_fps);
    fprintf('============================================================\n');

    %% Downsample calcium and spikes

    % Both models use the same downsampled calcium trace.
    % The downsampled spike train is used only as ground truth for evaluation.
    ds = downsample_calcium_and_spikes(calcium, spikes, original_fps, target_fps);

    calcium_ds = ds.calcium;
    spikes_ds = ds.spikes;
    fps = ds.actual_fps;

    fprintf('Actual fps: %.4f Hz\n', fps);
    fprintf('Downsample factor: %d\n', ds.downsample_factor);
    fprintf('Total spike count after downsampling: %.0f\n', ds.downsampled_spike_count);
    fprintf('Active spike bins after downsampling: %.0f\n\n', ds.downsampled_active_spike_bins);

    %% Run models

    fprintf('Running simple baseline...\n');
    baseline_result = run_simple_baseline(calcium_ds, fps, baseline_params);
    fprintf('Simple baseline predicted events: %d\n\n', baseline_result.n_predicted_events);

    fprintf('Running OASIS...\n');
    oasis_result = run_oasis_model(calcium_ds, fps, oasis_params);
    fprintf('OASIS predicted events: %d\n\n', oasis_result.n_predicted_events);

    %% Evaluate simple baseline

    for mode_idx = 1:length(evaluation_modes)

        mode = evaluation_modes{mode_idx};

        metrics = evaluate_event_prediction( ...
            baseline_result.predicted_events, ...
            spikes_ds, ...
            fps, ...
            tolerance_sec, ...
            mode, ...
            burst_gap_sec);

        new_row = metrics_to_table_row( ...
            'SimpleBaseline', ...
            neuron_idx, ...
            target_fps, ...
            fps, ...
            mode, ...
            metrics);

        results_table = [results_table; new_row];
    end

    %% Evaluate OASIS

    for mode_idx = 1:length(evaluation_modes)

        mode = evaluation_modes{mode_idx};

        metrics = evaluate_event_prediction( ...
            oasis_result.predicted_events, ...
            spikes_ds, ...
            fps, ...
            tolerance_sec, ...
            mode, ...
            burst_gap_sec);

        new_row = metrics_to_table_row( ...
            'OASIS', ...
            neuron_idx, ...
            target_fps, ...
            fps, ...
            mode, ...
            metrics);

        results_table = [results_table; new_row];
    end

    %% Print compact comparison for this sampling rate

    current_rows = results_table(results_table.target_fps == target_fps, :);

    fprintf('\nModel comparison results for %.1f Hz:\n', target_fps);
    fprintf('-------------------------------------------------------------------------------------------------------------\n');
    fprintf('%18s %15s %8s %8s %8s %10s %10s %10s %14s %14s\n', ...
        'Model', 'Mode', 'TP', 'FP', 'FN', ...
        'Precision', 'Recall', 'F1', ...
        'MedAbsErr', 'MeanBias');
    fprintf('-------------------------------------------------------------------------------------------------------------\n');

    for i = 1:height(current_rows)

        fprintf('%18s %15s %8d %8d %8d %10.3f %10.3f %10.3f %14.4f %14.4f\n', ...
            string(current_rows.model(i)), ...
            string(current_rows.evaluation_mode(i)), ...
            current_rows.TP(i), ...
            current_rows.FP(i), ...
            current_rows.FN(i), ...
            current_rows.precision(i), ...
            current_rows.recall(i), ...
            current_rows.F1(i), ...
            current_rows.median_abs_timing_error_sec(i), ...
            current_rows.mean_signed_timing_error_sec(i));
    end

    fprintf('-------------------------------------------------------------------------------------------------------------\n');
end

%% Print full comparison table

fprintf('\n\n============================================================\n');
fprintf('FULL MODEL COMPARISON TABLE\n');
fprintf('============================================================\n');

fprintf('--------------------------------------------------------------------------------------------------------------------------\n');
fprintf('%18s %10s %15s %8s %8s %8s %10s %10s %10s %14s %14s\n', ...
    'Model', 'TargetHz', 'Mode', 'TP', 'FP', 'FN', ...
    'Precision', 'Recall', 'F1', ...
    'MedAbsErr', 'MeanBias');
fprintf('--------------------------------------------------------------------------------------------------------------------------\n');

for i = 1:height(results_table)

    fprintf('%18s %10.1f %15s %8d %8d %8d %10.3f %10.3f %10.3f %14.4f %14.4f\n', ...
        string(results_table.model(i)), ...
        results_table.target_fps(i), ...
        string(results_table.evaluation_mode(i)), ...
        results_table.TP(i), ...
        results_table.FP(i), ...
        results_table.FN(i), ...
        results_table.precision(i), ...
        results_table.recall(i), ...
        results_table.F1(i), ...
        results_table.median_abs_timing_error_sec(i), ...
        results_table.mean_signed_timing_error_sec(i));
end

fprintf('--------------------------------------------------------------------------------------------------------------------------\n');

%% Save detailed results table

output_dir = fullfile('..', 'results', 'tables');

if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

output_file = fullfile(output_dir, 'baseline_vs_oasis_one_neuron_all_fps.csv');

writetable(results_table, output_file);

fprintf('\nSaved comparison table to:\n%s\n', output_file);

%% Local helper function

function row = metrics_to_table_row(model_name, neuron_idx, target_fps, actual_fps, evaluation_mode, metrics)
% metrics_to_table_row
%
% Converts one metrics struct into a one-row MATLAB table.
% This keeps the main script cleaner.

    row = table( ...
        string(model_name), ...
        neuron_idx, ...
        target_fps, ...
        actual_fps, ...
        string(evaluation_mode), ...
        metrics.tolerance_sec, ...
        metrics.tolerance_bins, ...
        metrics.burst_gap_sec, ...
        metrics.n_true_events, ...
        metrics.n_predicted_events, ...
        metrics.n_matched_events, ...
        metrics.TP, ...
        metrics.FP, ...
        metrics.FN, ...
        metrics.precision, ...
        metrics.recall, ...
        metrics.F1, ...
        metrics.mean_abs_timing_error_sec, ...
        metrics.median_abs_timing_error_sec, ...
        metrics.mean_signed_timing_error_sec, ...
        metrics.median_signed_timing_error_sec, ...
        metrics.std_timing_error_sec, ...
        'VariableNames', { ...
            'model', ...
            'neuron_idx', ...
            'target_fps', ...
            'actual_fps', ...
            'evaluation_mode', ...
            'tolerance_sec', ...
            'tolerance_bins', ...
            'burst_gap_sec', ...
            'n_true_events', ...
            'n_predicted_events', ...
            'n_matched_events', ...
            'TP', ...
            'FP', ...
            'FN', ...
            'precision', ...
            'recall', ...
            'F1', ...
            'mean_abs_timing_error_sec', ...
            'median_abs_timing_error_sec', ...
            'mean_signed_timing_error_sec', ...
            'median_signed_timing_error_sec', ...
            'std_timing_error_sec'});
end