%% RUN_MODEL_COMPARISON_ALL_DATA.m
% Goal:
%   Run model comparison across all available CRCNS .mat dataset files.
%
% Current models:
%   1. SimpleBaseline
%   2. OASIS
%
% Current sampling rates:
%   100, 50, 20, 10 Hz
%
% Current evaluation modes:
%   1. spike_bins
%   2. burst_onsets
%
% Output:
%   1. Detailed CSV:
%      one row per dataset x neuron/recording x fps x model x evaluation mode
%
%   2. Summary CSV:
%      one row per model x fps x evaluation mode
%
% Design note:
%   This script is intentionally model-extensible.
%   To add a future model, add its name to model_names and add one case
%   inside run_model_by_name() at the bottom of this file.

clear; clc; close all;

%% Add project paths

addpath(fullfile('..', 'src'));
addpath(genpath(fullfile('..', 'external', 'OASIS_matlab')));

%% Project folders

data_dir = fullfile('..', 'data', 'MockData');
output_dir = fullfile('..', 'results', 'tables');

if ~exist(output_dir, 'dir')
    mkdir(output_dir);
end

%% Find all dataset files

dataset_files = dir(fullfile(data_dir, 'data.*.train.preprocessed.mat'));

if isempty(dataset_files)
    error('No dataset files found in: %s', data_dir);
end

fprintf('Found %d dataset files.\n\n', length(dataset_files));

%% Experiment settings

target_fps_list = [100, 50, 20, 10];

evaluation_modes = {'spike_bins', 'burst_onsets'};

tolerance_sec = 0.10;
burst_gap_sec = 0.10;

%% Model list

% To add another model later:
%   1. Add its name here.
%   2. Add its parameters below.
%   3. Add a case in run_model_by_name().
model_names = {'SimpleBaseline', 'OASIS'};

%% Simple baseline parameters

baseline_params = struct();

baseline_params.smoothing_window_sec = 0.2;
baseline_params.derivative_weight = 0.7;
baseline_params.amplitude_weight = 0.3;
baseline_params.event_score_threshold = 0.9;
baseline_params.min_event_distance_sec = 0.10;

%% OASIS parameters

oasis_params = struct();

oasis_params.ar_model = 'ar1';
oasis_params.method = 'foopsi';
oasis_params.optimize_b = true;
oasis_params.optimize_pars = true;

% Not final. These will later be optimized on validation data.
oasis_params.oasis_threshold_z = 1.5;
oasis_params.min_event_distance_sec = 0.10;

%% Store all model parameters in one struct

model_params = struct();
model_params.SimpleBaseline = baseline_params;
model_params.OASIS = oasis_params;

%% Prepare detailed results table

detailed_results = table();

%% Main loop

for file_idx = 1:length(dataset_files)

    dataset_name = dataset_files(file_idx).name;
    dataset_path = fullfile(dataset_files(file_idx).folder, dataset_name);
    dataset_id = parse_dataset_id(dataset_name);

    fprintf('\n============================================================\n');
    fprintf('Loading dataset file %d/%d: %s\n', file_idx, length(dataset_files), dataset_name);
    fprintf('============================================================\n');

    raw = load(dataset_path);

    if ~isfield(raw, 'data')
        error('File %s does not contain variable named "data".', dataset_name);
    end

    data = raw.data;

    fprintf('Number of recordings in file: %d\n', numel(data));

    for recording_idx = 1:numel(data)

        rec = data{recording_idx};

        calcium = double(rec.calcium(:));
        spikes = double(rec.spikes(:));
        original_fps = double(rec.fps);

        if isfield(rec, 'cell_num')
            cell_num = double(rec.cell_num);
        else
            cell_num = recording_idx;
        end

        fprintf('\nDataset %d | Recording %d/%d | Cell %g\n', ...
            dataset_id, recording_idx, numel(data), cell_num);

        for fps_idx = 1:length(target_fps_list)

            target_fps = target_fps_list(fps_idx);

            fprintf('  Target FPS: %.1f\n', target_fps);

            try
                ds = downsample_calcium_and_spikes( ...
                    calcium, ...
                    spikes, ...
                    original_fps, ...
                    target_fps);

                calcium_ds = ds.calcium;
                spikes_ds = ds.spikes;
                actual_fps = ds.actual_fps;

            catch ME
                fprintf('    Downsampling failed: %s\n', ME.message);

                % If downsampling fails, log failure rows for all models/modes.
                for model_idx = 1:length(model_names)
                    for mode_idx = 1:length(evaluation_modes)

                        failure_row = failure_table_row( ...
                            dataset_name, dataset_id, recording_idx, cell_num, ...
                            target_fps, NaN, model_names{model_idx}, ...
                            evaluation_modes{mode_idx}, ...
                            'downsampling_failed', ME.message);

                        detailed_results = [detailed_results; failure_row];
                    end
                end

                continue;
            end

            for model_idx = 1:length(model_names)

                model_name = model_names{model_idx};

                fprintf('    Running model: %s\n', model_name);

                try
                    model_result = run_model_by_name( ...
                        model_name, ...
                        calcium_ds, ...
                        actual_fps, ...
                        model_params);

                    predicted_events = model_result.predicted_events;
                    n_predicted_events = model_result.n_predicted_events;

                catch ME
                    fprintf('      Model failed: %s\n', ME.message);

                    % If model fails, log failure rows for all evaluation modes.
                    for mode_idx = 1:length(evaluation_modes)

                        failure_row = failure_table_row( ...
                            dataset_name, dataset_id, recording_idx, cell_num, ...
                            target_fps, actual_fps, model_name, ...
                            evaluation_modes{mode_idx}, ...
                            'model_failed', ME.message);

                        detailed_results = [detailed_results; failure_row];
                    end

                    continue;
                end

                for mode_idx = 1:length(evaluation_modes)

                    mode = evaluation_modes{mode_idx};

                    try
                        metrics = evaluate_event_prediction( ...
                            predicted_events, ...
                            spikes_ds, ...
                            actual_fps, ...
                            tolerance_sec, ...
                            mode, ...
                            burst_gap_sec);

                        new_row = metrics_to_table_row( ...
                            dataset_name, ...
                            dataset_id, ...
                            recording_idx, ...
                            cell_num, ...
                            target_fps, ...
                            actual_fps, ...
                            model_name, ...
                            mode, ...
                            metrics, ...
                            n_predicted_events, ...
                            'ok', ...
                            "");

                        detailed_results = [detailed_results; new_row];

                    catch ME
                        fprintf('      Evaluation failed: %s\n', ME.message);

                        failure_row = failure_table_row( ...
                            dataset_name, dataset_id, recording_idx, cell_num, ...
                            target_fps, actual_fps, model_name, mode, ...
                            'evaluation_failed', ME.message);

                        detailed_results = [detailed_results; failure_row];
                    end
                end
            end
        end
    end
end

%% Save detailed results

detailed_output_file = fullfile(output_dir, 'model_results_detailed.csv');

writetable(detailed_results, detailed_output_file);

fprintf('\nSaved detailed results to:\n%s\n', detailed_output_file);

%% Create and save summary results

summary_results = summarize_results_table(detailed_results);

summary_output_file = fullfile(output_dir, 'model_results_summary.csv');

writetable(summary_results, summary_output_file);

fprintf('\nSaved summary results to:\n%s\n', summary_output_file);

%% Print compact summary

fprintf('\n============================================================\n');
fprintf('SUMMARY RESULTS\n');
fprintf('============================================================\n');

fprintf('%18s %10s %15s %10s %10s %10s %14s %14s\n', ...
    'Model', 'FPS', 'Mode', 'MeanF1', 'MedF1', 'MeanRec', ...
    'MedAbsErr', 'TimeWRecall');

fprintf('-----------------------------------------------------------------------------------------------------\n');

for i = 1:height(summary_results)

    fprintf('%18s %10.1f %15s %10.3f %10.3f %10.3f %14.4f %14.4f\n', ...
        string(summary_results.model(i)), ...
        summary_results.target_fps(i), ...
        string(summary_results.evaluation_mode(i)), ...
        summary_results.mean_F1(i), ...
        summary_results.median_F1(i), ...
        summary_results.mean_recall(i), ...
        summary_results.mean_median_abs_timing_error_sec(i), ...
        summary_results.mean_timing_weighted_recall(i));
end

fprintf('-----------------------------------------------------------------------------------------------------\n');

fprintf('\nDone.\n');

%% Local helper functions

function model_result = run_model_by_name(model_name, calcium, fps, model_params)
% run_model_by_name
%
% Runs one model using a shared interface.
%
% Input:
%   model_name   - name of model to run
%   calcium      - calcium trace
%   fps          - sampling rate
%   model_params - struct containing parameter structs for each model
%
% Output:
%   model_result - struct that must contain:
%       predicted_events
%       n_predicted_events

    switch model_name

        case 'SimpleBaseline'

            model_result = run_simple_baseline( ...
                calcium, ...
                fps, ...
                model_params.SimpleBaseline);

        case 'OASIS'

            model_result = run_oasis_model( ...
                calcium, ...
                fps, ...
                model_params.OASIS);

        otherwise

            error('Unknown model name: %s', model_name);
    end
end

function row = metrics_to_table_row(dataset_name, dataset_id, recording_idx, cell_num, ...
    target_fps, actual_fps, model_name, evaluation_mode, metrics, ...
    n_predicted_events_from_model, status, error_message)
% metrics_to_table_row
%
% Converts one metrics struct into one row in the detailed results table.

    row = table( ...
        string(dataset_name), ...
        dataset_id, ...
        recording_idx, ...
        cell_num, ...
        target_fps, ...
        actual_fps, ...
        string(model_name), ...
        string(evaluation_mode), ...
        string(status), ...
        string(error_message), ...
        metrics.tolerance_sec, ...
        metrics.tolerance_bins, ...
        metrics.burst_gap_sec, ...
        metrics.n_true_events, ...
        metrics.n_predicted_events, ...
        n_predicted_events_from_model, ...
        metrics.n_matched_events, ...
        metrics.TP, ...
        metrics.FP, ...
        metrics.FN, ...
        metrics.precision, ...
        metrics.recall, ...
        metrics.F1, ...
        metrics.mean_abs_timing_error_sec, ...
        metrics.median_abs_timing_error_sec, ...
        metrics.mean_signed_timing_error_sec, ...
        metrics.median_signed_timing_error_sec, ...
        metrics.std_timing_error_sec, ...
        metrics.mean_timing_score, ...
        metrics.total_timing_score, ...
        metrics.timing_weighted_recall, ...
        'VariableNames', { ...
            'dataset_name', ...
            'dataset_id', ...
            'recording_idx', ...
            'cell_num', ...
            'target_fps', ...
            'actual_fps', ...
            'model', ...
            'evaluation_mode', ...
            'status', ...
            'error_message', ...
            'tolerance_sec', ...
            'tolerance_bins', ...
            'burst_gap_sec', ...
            'n_true_events', ...
            'n_predicted_events', ...
            'n_predicted_events_from_model', ...
            'n_matched_events', ...
            'TP', ...
            'FP', ...
            'FN', ...
            'precision', ...
            'recall', ...
            'F1', ...
            'mean_abs_timing_error_sec', ...
            'median_abs_timing_error_sec', ...
            'mean_signed_timing_error_sec', ...
            'median_signed_timing_error_sec', ...
            'std_timing_error_sec', ...
            'mean_timing_score', ...
            'total_timing_score', ...
            'timing_weighted_recall'});
end

function row = failure_table_row(dataset_name, dataset_id, recording_idx, cell_num, ...
    target_fps, actual_fps, model_name, evaluation_mode, status, error_message)
% failure_table_row
%
% Creates a row for failed downsampling/model/evaluation attempts.
% Numeric metrics are filled with NaN.

    row = table( ...
        string(dataset_name), ...
        dataset_id, ...
        recording_idx, ...
        cell_num, ...
        target_fps, ...
        actual_fps, ...
        string(model_name), ...
        string(evaluation_mode), ...
        string(status), ...
        string(error_message), ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        NaN, ...
        'VariableNames', { ...
            'dataset_name', ...
            'dataset_id', ...
            'recording_idx', ...
            'cell_num', ...
            'target_fps', ...
            'actual_fps', ...
            'model', ...
            'evaluation_mode', ...
            'status', ...
            'error_message', ...
            'tolerance_sec', ...
            'tolerance_bins', ...
            'burst_gap_sec', ...
            'n_true_events', ...
            'n_predicted_events', ...
            'n_predicted_events_from_model', ...
            'n_matched_events', ...
            'TP', ...
            'FP', ...
            'FN', ...
            'precision', ...
            'recall', ...
            'F1', ...
            'mean_abs_timing_error_sec', ...
            'median_abs_timing_error_sec', ...
            'mean_signed_timing_error_sec', ...
            'median_signed_timing_error_sec', ...
            'std_timing_error_sec', ...
            'mean_timing_score', ...
            'total_timing_score', ...
            'timing_weighted_recall'});
end

function dataset_id = parse_dataset_id(dataset_name)
% parse_dataset_id
%
% Extracts dataset number from names like:
%   data.1.train.preprocessed.mat

    tokens = regexp(dataset_name, 'data\.(\d+)\.train', 'tokens');

    if isempty(tokens)
        dataset_id = NaN;
    else
        dataset_id = str2double(tokens{1}{1});
    end
end

function summary_table = summarize_results_table(detailed_results)
% summarize_results_table
%
% Aggregates detailed results across neurons/recordings.
%
% Grouping:
%   model x target_fps x evaluation_mode
%
% Only rows with status == "ok" are included.

    ok_rows = detailed_results(detailed_results.status == "ok", :);

    if isempty(ok_rows)
        warning('No successful result rows found. Summary table will be empty.');
        summary_table = table();
        return;
    end

    group_vars = {'model', 'target_fps', 'evaluation_mode'};

    [G, group_model, group_fps, group_mode] = findgroups( ...
        ok_rows.model, ...
        ok_rows.target_fps, ...
        ok_rows.evaluation_mode);

    n_groups = max(G);

    summary_table = table();

    for g = 1:n_groups

        idx = G == g;
        group_data = ok_rows(idx, :);

        n_rows = height(group_data);
        n_unique_recordings = height(unique(group_data(:, {'dataset_id', 'recording_idx'})));

        F1_values = group_data.F1;
        precision_values = group_data.precision;
        recall_values = group_data.recall;
        median_abs_timing_values = group_data.median_abs_timing_error_sec;
        mean_signed_timing_values = group_data.mean_signed_timing_error_sec;
        timing_weighted_recall_values = group_data.timing_weighted_recall;

        row = table( ...
            group_model(g), ...
            group_fps(g), ...
            group_mode(g), ...
            n_rows, ...
            n_unique_recordings, ...
            mean(F1_values, 'omitnan'), ...
            median(F1_values, 'omitnan'), ...
            std(F1_values, 'omitnan'), ...
            std(F1_values, 'omitnan') / sqrt(sum(~isnan(F1_values))), ...
            mean(precision_values, 'omitnan'), ...
            median(precision_values, 'omitnan'), ...
            mean(recall_values, 'omitnan'), ...
            median(recall_values, 'omitnan'), ...
            mean(median_abs_timing_values, 'omitnan'), ...
            median(median_abs_timing_values, 'omitnan'), ...
            mean(mean_signed_timing_values, 'omitnan'), ...
            median(mean_signed_timing_values, 'omitnan'), ...
            mean(timing_weighted_recall_values, 'omitnan'), ...
            median(timing_weighted_recall_values, 'omitnan'), ...
            'VariableNames', { ...
                'model', ...
                'target_fps', ...
                'evaluation_mode', ...
                'n_result_rows', ...
                'n_unique_recordings', ...
                'mean_F1', ...
                'median_F1', ...
                'std_F1', ...
                'sem_F1', ...
                'mean_precision', ...
                'median_precision', ...
                'mean_recall', ...
                'median_recall', ...
                'mean_median_abs_timing_error_sec', ...
                'median_median_abs_timing_error_sec', ...
                'mean_signed_timing_error_sec', ...
                'median_signed_timing_error_sec', ...
                'mean_timing_weighted_recall', ...
                'median_timing_weighted_recall'});

        summary_table = [summary_table; row];
    end
end